apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-jenkins-argocd-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yungsnowx/quarkus-jenkins-argocd.git
    targetRevision: nightly
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: quarkus-jenkins-argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true